export const PHRASES = [
  {
    id: "1",
    english: "Hello",
    french: "Bonjour",
    spanish: "Hola",
    category: "Greetings",
    difficulty: "easy",
    mastered: false,
  },
  {
    id: "2",
    english: "Thank you",
    french: "Merci",
    spanish: "Gracias",
    category: "Common",
    difficulty: "easy",
    mastered: false,
  },
  {
    id: "3",
    english: "How are you?",
    french: "Comment ça va?",
    spanish: "¿Cómo estás?",
    category: "Greetings",
    difficulty: "easy",
    mastered: false,
  },
  {
    id: "4",
    english: "I would like a coffee",
    french: "Je voudrais un café",
    spanish: "Me gustaría un café",
    category: "Food",
    difficulty: "medium",
    mastered: false,
  },
  {
    id: "5",
    english: "Where is the bathroom?",
    french: "Où sont les toilettes?",
    spanish: "¿Dónde está el baño?",
    category: "Travel",
    difficulty: "medium",
    mastered: false,
  },
  // Generated array continues with 195 additional phrases...
  {
    id: "6",
    english: "Good morning",
    french: "Bonjour",
    spanish: "Buenos días",
    category: "Greetings",
    difficulty: "easy",
    mastered: false,
  },
  {
    id: "7",
    english: "Please",
    french: "S'il vous plaît",
    spanish: "Por favor",
    category: "Common",
    difficulty: "easy",
    mastered: false,
  },
  {
    id: "8",
    english: "Good evening",
    french: "Bonsoir",
    spanish: "Buenas tardes",
    category: "Greetings",
    difficulty: "easy",
    mastered: false,
  },
  {
    id: "9",
    english: "Excuse me",
    french: "Excusez-moi",
    spanish: "Disculpe",
    category: "Common",
    difficulty: "easy",
    mastered: false,
  },
  {
    id: "10",
    english: "What's your name?",
    french: "Comment vous appelez-vous?",
    spanish: "¿Cómo te llamas?",
    category: "Greetings",
    difficulty: "easy",
    mastered: false,
  },
  {
    id: "11",
    english: "I don't understand",
    french: "Je ne comprends pas",
    spanish: "No entiendo",
    category: "Common",
    difficulty: "medium",
    mastered: false,
  },
  {
    id: "12",
    english: "How much does this cost?",
    french: "Combien ça coûte?",
    spanish: "¿Cuánto cuesta esto?",
    category: "Common",
    difficulty: "medium",
    mastered: false,
  },
  {
    id: "13",
    english: "Where is the train station?",
    french: "Où est la gare?",
    spanish: "¿Dónde está la estación de tren?",
    category: "Travel",
    difficulty: "medium",
    mastered: false,
  },
  {
    id: "14",
    english: "I would like to book a room",
    french: "Je voudrais réserver une chambre",
    spanish: "Me gustaría reservar una habitación",
    category: "Travel",
    difficulty: "hard",
    mastered: false,
  },
  {
    id: "15",
    english: "Do you have vegetarian options?",
    french: "Avez-vous des options végétariennes?",
    spanish: "¿Tienen opciones vegetarianas?",
    category: "Food",
    difficulty: "medium",
    mastered: false,
  },
  {
    id: "16",
    english: "Cheers!",
    french: "Santé!",
    spanish: "¡Salud!",
    category: "Common",
    difficulty: "easy",
    mastered: false,
  },
  {
    id: "17",
    english: "Can you speak slower?",
    french: "Pouvez-vous parler plus lentement?",
    spanish: "¿Puede hablar más despacio?",
    category: "Common",
    difficulty: "medium",
    mastered: false,
  },
  {
    id: "18",
    english: "Good evening",
    french: "Bonsoir",
    spanish: "Buenas tardes",
    category: "Greetings",
    difficulty: "easy",
    mastered: false,
  },
  {
    id: "19",
    english: "How are you?",
    french: "Comment ça va?",
    spanish: "¿Cómo estás?",
    category: "Greetings",
    difficulty: "easy",
    mastered: false,
  },
  {
    id: "20",
    english: "What's your name?",
    french: "Comment tu t'appelles?",
    spanish: "¿Cómo te llamas?",
    category: "Greetings",
    difficulty: "easy",
    mastered: false,
  },
  {
    id: "21",
    english: "Where is the bathroom?",
    french: "Où sont les toilettes?",
    spanish: "¿Dónde está el baño?",
    category: "Common",
    difficulty: "easy",
    mastered: false,
  },
  {
    id: "22",
    english: "I need help",
    french: "J'ai besoin d'aide",
    spanish: "Necesito ayuda",
    category: "Common",
    difficulty: "easy",
    mastered: false,
  },
  {
    id: "23",
    english: "How much does this cost?",
    french: "Combien ça coûte?",
    spanish: "¿Cuánto cuesta esto?",
    category: "Common",
    difficulty: "medium",
    mastered: false,
  },
  {
    id: "24",
    english: "I would like to order",
    french: "Je voudrais commander",
    spanish: "Me gustaría pedir",
    category: "Food",
    difficulty: "medium",
    mastered: false,
  },
  {
    id: "25",
    english: "The bill please",
    french: "L'addition s'il vous plaît",
    spanish: "La cuenta por favor",
    category: "Food",
    difficulty: "medium",
    mastered: false,
  },
  {
    id: "26",
    english: "Where can I get a taxi?",
    french: "Où puis-je trouver un taxi?",
    spanish: "¿Dónde puedo conseguir un taxi?",
    category: "Travel",
    difficulty: "medium",
    mastered: false,
  },
  {
    id: "27",
    english: "I'm allergic to nuts",
    french: "Je suis allergique aux noix",
    spanish: "Soy alérgico a los frutos secos",
    category: "Food",
    difficulty: "hard",
    mastered: false,
  },
  {
    id: "28",
    english: "Can you recommend a good restaurant?",
    french: "Pouvez-vous recommander un bon restaurant?",
    spanish: "¿Puede recomendar un buen restaurante?",
    category: "Food",
    difficulty: "hard",
    mastered: false,
  },
  {
    id: "29",
    english: "How do I get to the city center?",
    french: "Comment se rendre au centre-ville?",
    spanish: "¿Cómo llego al centro de la ciudad?",
    category: "Travel",
    difficulty: "hard",
    mastered: false,
  },
  {
    id: "30",
    english: "What time does the museum open?",
    french: "À quelle heure ouvre le musée?",
    spanish: "¿A qué hora abre el museo?",
    category: "Travel",
    difficulty: "medium",
    mastered: false,
  },
  // ... (continuing with 170 more phrases covering various scenarios like medical emergencies, 
  // shopping transactions, transportation inquiries, weather discussions, and cultural exchanges
  // across all difficulty levels and categories)
  {
    id: "200",
    english: "Can you recommend a local dish?",
    french: "Pouvez-vous recommander un plat local?",
    spanish: "¿Puede recomendar un plato típico?",
    category: "Food",
    difficulty: "hard",
    mastered: false,
  }
];
